### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by afby** [Raptor3um/Raptoreum#125]
Hello,
I get this error message when installing :(
Linux 5.16.0-kali1-amd64 #1 SMP PREEMPT Debian 5.16.7-2kali1 (2022-02-10) x86_64 GNU/Linux

`└─$ src/install.py            
[2022-03-04 09:30:29][install][INFO]: FACT Installer 1.2
[2022-03-04 09:30:29][common][INFO]: Updating system
[sudo] Mot de passe de afby : 
[2022-03-04 09:30:46][install][INFO]: Installing apt-transport-https autoconf automake build-essential git libtool python3 python3-dev unzip libfuzzy-dev libmagic-dev
[2022-03-04 09:31:03][common][INFO]: Installing python3 pip
[2022-03-04 09:34:45][install][INFO]: Installing variety/variety
[2022-03-04 09:36:51][frontend][INFO]: Install static jstree content
[2022-03-04 09:36:53][frontend][INFO]: Install static angularJS content
[2022-03-04 09:36:53][frontend][INFO]: Install static charts.js content
[2022-03-04 09:36:54][frontend][INFO]: Installing highlight js
[2022-03-04 09:36:58][frontend][INFO]: Install static https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css content
[2022-03-04 09:36:58][frontend][INFO]: Install static https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.standalone.css content
[2022-03-04 09:36:59][frontend][INFO]: Install static https://unpkg.com/vis-network@8.5.6/styles/vis-network.min.css content
[2022-03-04 09:37:00][frontend][INFO]: Install static https://cdn.jsdelivr.net/npm/diff2html/bundles/css/diff2html.min.css content
[2022-03-04 09:37:00][frontend][INFO]: Install static https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js content
[2022-03-04 09:37:01][frontend][INFO]: Install static https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js content
[2022-03-04 09:37:01][frontend][INFO]: Install static https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js content
[2022-03-04 09:37:01][frontend][INFO]: Install static https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js content
[2022-03-04 09:37:02][frontend][INFO]: Install static https://raw.githubusercontent.com/moment/moment/develop/moment.js content
[2022-03-04 09:37:02][frontend][INFO]: Install static https://unpkg.com/vis-network@8.5.6/standalone/umd/vis-network.min.js content
[2022-03-04 09:37:03][frontend][INFO]: Install static https://cdn.jsdelivr.net/npm/diff2html/bundles/js/diff2html-ui.min.js content
[2022-03-04 09:37:04][frontend][INFO]: Install static https://use.fontawesome.com/releases/v5.13.0/fontawesome-free-5.13.0-web.zip content
[2022-03-04 09:37:08][frontend][INFO]: Creating directory for authentication
[2022-03-04 09:37:08][frontend][INFO]: Initializing docker container for radare
[2022-03-04 09:37:33][frontend][INFO]: Pulling pdf report container
[2022-03-04 09:44:13][db][INFO]: Setting up mongo database
[2022-03-04 09:44:20][install][INFO]: Installing mongodb-org
[2022-03-04 09:45:29][db][INFO]: Initialize database
[2022-03-04 09:45:34][install][INFO]: Installing libjpeg-dev libssl-dev binutils file openssl bison flex pkg-config
[2022-03-04 09:46:54][backend][INFO]: Skipping yara installation: Already installed and up to date
[2022-03-04 09:46:54][backend][INFO]: Installing checksec.sh
[2022-03-04 09:46:54][backend][INFO]: Pulling fact extraction container
[2022-03-04 09:54:50][backend][INFO]: Installing linter plugin.
[2022-03-04 09:57:29][backend][INFO]: Finished installing linter plugin.

[2022-03-04 09:57:29][backend][INFO]: Installing cve_lookup plugin.
[2022-03-04 10:05:43][backend][INFO]: Finished installing cve_lookup plugin.

[2022-03-04 10:05:44][backend][INFO]: Installing file_system_metadata plugin.
[2022-03-04 10:06:19][backend][INFO]: Finished installing file_system_metadata plugin.

[2022-03-04 10:06:20][backend][INFO]: Installing software_components plugin.
[2022-03-04 10:10:32][backend][INFO]: Finished installing software_components plugin.

[2022-03-04 10:10:32][backend][INFO]: Installing cwe_checker plugin.
[2022-03-04 10:13:20][backend][INFO]: Finished installing cwe_checker plugin.

[2022-03-04 10:13:20][backend][INFO]: Installing kernel_config plugin.
[2022-03-04 10:13:52][backend][INFO]: Finished installing kernel_config plugin.

[2022-03-04 10:13:52][backend][INFO]: Installing crypto_hints plugin.
[2022-03-04 10:13:56][backend][INFO]: Finished installing crypto_hints plugin.

[2022-03-04 10:13:57][backend][INFO]: Installing ip_and_uri_finder plugin.
[2022-03-04 10:14:55][backend][INFO]: Finished installing ip_and_uri_finder plugin.

[2022-03-04 10:14:55][backend][INFO]: Installing oms plugin.
[2022-03-04 10:15:53][backend][INFO]: Finished installing oms plugin.

[2022-03-04 10:15:54][backend][INFO]: Installing users_and_passwords plugin.
[2022-03-04 10:17:42][install][ERROR]: Failed to run make -s clean && make -sj$(nproc):
In file included from argon2_core_plug.c:32:
blake2.h:112:5: error: size of array element is not a multiple of its alignment
  112 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
blake2.h:113:5: error: size of array element is not a multiple of its alignment
  113 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
make[1]: *** [Makefile:1596 : argon2_core_plug.o] Erreur 1
make[1]: *** Attente des tâches non terminées....
make: *** [Makefile:190 : default] Erreur 2

Traceback (most recent call last):
  File "/home/afby/FACT_core/src/install.py", line 183, in <module>
    install()
  File "/home/afby/FACT_core/src/install.py", line 151, in install
    install_fact_components(args, distribution, none_chosen, skip_docker)
  File "/home/afby/FACT_core/src/install.py", line 171, in install_fact_components
    backend(skip_docker, distribution)
  File "/home/afby/FACT_core/src/install/backend.py", line 45, in main
    _install_plugins(distribution, skip_docker)
  File "/home/afby/FACT_core/src/install/backend.py", line 113, in _install_plugins
    plugin_installer.install()
  File "/home/afby/FACT_core/src/plugins/installer.py", line 34, in install
    self.build()
  File "/home/afby/FACT_core/src/plugins/analysis/users_and_passwords/install.py", line 50, in build
    run_cmd_with_logging('make -s clean && make -sj$(nproc)', shell=True)
  File "/home/afby/FACT_core/src/helperFunctions/install.py", line 222, in run_cmd_with_logging
    raise err
  File "/home/afby/FACT_core/src/helperFunctions/install.py", line 216, in run_cmd_with_logging
    subprocess.run(cmd_, stdout=PIPE, stderr=PIPE, encoding='UTF-8', shell=shell, check=True, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'make -s clean && make -sj$(nproc)' returned non-zero exit status 2.
                                                                                                             `

**Comment by Bigpiggy01** [comment]
1) Kali isn't a supported distro. 2) There is no install.py in the code from github. 

If you are trying to build you follow the documentation for a UNIX build.
