### ISSUE TITLE
Crash in Qt Wallet when sending exactly 21M RTM

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/Raptoreum#129]
### Can you reliably reproduce the issue?
1. From the Qt wallet, attempt to send exactly 21M RTM

### Expected behaviour
It should provide an error (if 21M + Tx Fees exceed the limit) and refuse, or allow the transaction and not crash.

### Actual behaviour

Qt crashes with the following message:
```
Exception: type=std::runtime_error, what="GetValueOut: value out of range"
```

**Comment by CodeIsTheKey** [comment]
Call stack (from develop)
```
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff795e859 in __GI_abort () at abort.c:79
#2  0x00005555557db431 in terminate_handler () at stacktraces.cpp:780
#3  0x00007ffff7bf338c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7bf33f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7bf36a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555817341 in CWallet::GetCredit () at wallet/wallet.cpp:2008
#7  0x0000555555f0f20f in CWalletTx::GetCredit () at wallet/wallet.cpp:2439
#8  0x0000555555ebb149 in MakeWalletTx () at interfaces/wallet.cpp:84
#9  0x0000555555ebb640 in getWalletTx () at interfaces/wallet.cpp:324
#10 0x00005555559b4fab in TransactionTablePriv::updateWallet () at qt/transactiontablemodel.cpp:127
#11 0x00005555559b1acd in TransactionTableModel::updateTransaction () at qt/transactiontablemodel.cpp:263
#12 0x00005555567baf0a in QObject::event(QEvent*) ()
#13 0x00005555568e5de6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#14 0x00005555568ef5b8 in QApplication::notify(QObject*, QEvent*) ()
#15 0x000055555678a64a in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#16 0x000055555678d7fc in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#17 0x00005555567e1d87 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#18 0x000055555627f151 in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#19 0x0000555556788f36 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#20 0x0000555556a6e41d in QDialog::exec() ()
#21 0x0000555556aa1bb6 in showNewMessageBox(QWidget*, QMessageBox::Icon, QString const&, QString const&, QFlags<QMessageBox::StandardButton>, QMessageBox::StandardButton) ()
#22 0x0000555555886a38 in BitcoinApplication::handleRunawayException () at qt/raptoreum.cpp:541
#23 0x00005555556bd433 in main () at qt/raptoreum.cpp:839
```

**Comment by npq7721** [comment]
solution for this is to increase limit from 21M to 21B and this is a consensus rule so may want to add a hardfork block for it and use the same hard fork block chain params for the up coming hardfork

**Comment by CodeIsTheKey** [comment]
Resolved with https://github.com/Raptor3um/raptoreum/pull/187
